### ISSUE TITLE
:sparkles: feat: APAスタイルの斜体対応

### ISSUE THREAD

**Issue by YouTuber-repopo** [Kokecoco/KITs#37]
### Issueの概要

- APAスタイル作成後の結果表示部分を`<textarea>`から`<div>`に変更する
- APAスタイル作成時のタイトル部分は斜体にする
- 結果表示部分の`<div>`は`contenteditable="true"`を適用させる

### Issueの理由

- APAスタイル作成時タイトルは斜体にしてほしいとの要望が多数あった
- `<div>`を`contenteditable="true"`にすることで、`<textarea>`と同じように結果を直接編集できるようになる

### 備考

- contenteditableについては以下を参照 \
[Mozilla](https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/contenteditable)
- HTMLで斜体にしてれば多分ドキュメントにコピペしても斜体になるはず

**Comment by Kokecoco** [comment]
> HTMLで斜体にしてれば多分ドキュメントにコピペしても斜体になるはず

できるよ
